#!/usr/bin/env bash

SCRIPT_DIR="${HOME}/.scripts/site-control"

# Decoration ----------------------------------------------------------------------------
R='\033[0;31m'
G='\033[0;32m'
DG='\033[2;32m'
Y='\033[0;33m'
B='\033[0;34m'
M='\033[0;35m'
C='\033[0;36m'
NC='\033[0m'

banner() { printf "${M}============ ${B}%s ${M}============${NC} %s\n" "$1" "${2:+\n$2}"; }

ERR() { echo -e "${R}✗${NC} $1" >&2; }
OK() { echo -e "${G}✓${NC} $1"; }
WARN() { echo -e "${Y}WARNING: $1${NC}" >&2; }
TODO() { echo -e "${Y}TODO: $1${NC}" >&2; }
DEBUG() { echo -e "${C}DEBUG: ${B}$1${NC}" >&2; }

# Initialization -------------------------------------------------------------------------
script_init() {
    if [ -f "$REGISTRY" ]; then
        return 0;
    fi
    REGISTRY="${SCRIPT_DIR}/registry.yaml"
    if [[ ! -f "$REGISTRY" ]]; then
        ERR "Registry file missing from '${G}$REGISTRY${NC}'"
        echo "Unable to obtain global values."
        echo "Script will now exit..."
        exit 1
    fi
    if ! CFG_KEYS=$(yq e '.sites | keys[] | .' "$REGISTRY" 2>/dev/null); then
        WARN "No registered sites found."
    fi
}
script_init

# Helpers -------------------------------------------------------------------------------
has_local_config() {
    if [ -f "${PWD}/cfg.yaml" ]; then
        return 0;
    fi
    return 1;
}

has_script_config() {
    if [ -f "${REGISTRY}" ]; then
        return 0;
    fi
    return 1;
}

get_all_site_names() {
    echo "$CFG_KEYS"
}

get_version_info() {
    local path="$1"

    local prod_version; prod_version=$(
        git -C "$path" describe --abbrev=0 2>/dev/null || echo "unknown"
    )
    local dev_version; dev_version=$(
        git -C "$path" tag --sort=-version:refname | head -1 2>/dev/null || echo "unknown"
    )
    if [[ "$prod_version" == "unknown" && "$dev_version" != "unknown" ]]; then
        prod_version="$dev_version"
    fi

    local commits; commits=$(
        git -C "$path" rev-list --count main..HEAD 2>/dev/null || echo "0"
    )
    local current_branch; current_branch=$(
        git -C "$path" branch --show-current 2>/dev/null || echo "unknown"
    )

    echo "$prod_version|$dev_version|$commits|$current_branch"
}

update_version_info() {
    local site="$1"   
    local path; if ! path=$(yq e ".sites.${site}.paths.root" "$REGISTRY"); then
        ERR "Updating version info failed: site root path not found"
    fi

    local vinfo; vinfo=$(get_version_info "$path")
    local vprod; vprod=$(echo "$vinfo" | cut -d'|' -f1)
    local vdev; vdev=$(echo "$vinfo" | cut -d'|' -f2)
    local commits; commits=$(echo "$vinfo" | cut -d'|' -f3)
    local branch; branch=$(echo "$vinfo" | cut -d'|' -f4)
    
    yq -i "with(.sites.${site};
        .dev_version = \"${vdev}\" |
        .prod_version = \"${vprod}\" |
        .commit_diff = ${commits} |
        .dev_branch = \"${branch}\"
    )" "${REGISTRY}"
}

update_timestamp() {
    local site; site="$1"
    local mode; mode="${2}"
    local timestamp; timestamp=$(date +'%d%b%Y %H:%M:%S')
    yq -i ".sites.${site}.last_${mode} = \"${timestamp}\"" "$REGISTRY"
}

create_systemd_service() {
    local site="$1"
    local prod_dir; prod_dir=$(yq e ".sites.${site}.paths.prod" "$REGISTRY")
    local unit; unit="site-${site}.service"

    cat > "/tmp/${unit}" <<EOF
[Unit]
Description=${site^} Log Service
After=network.target

[Service]
Type=simple
User=kh
Group=kh
WorkingDirectory=${prod_dir}/backend
ExecStart=${prod_dir}/${site}-backend
Restart=always
RestartSec=5
Environment=ENVIRONMENT=production
EnvironmentFile=${HOME}/sites/.prod/${site}/backend/.env

[Install]
WantedBy=multi-user.target
EOF
    sudo cp "/tmp/${unit}" "/etc/systemd/system/${unit}"
    OK "Created systemd service file: ${G}/etc/systemd/system/${unit}${NC}"
}

# YAML ----------------------------------------------------------------------------------
get_and_incr_site_count() {
    local site_count=$((1 + $(yq e '.global.site_count' "$REGISTRY")))
    yq -i ".global.site_count = $site_count" "$REGISTRY"
    echo $site_count
}

make_local_config() {
    local site="$1"
    local local_cfg; local_cfg="${PWD}/cfg.yaml"
    touch "$local_cfg"
    local bport; bport=$(yq e ".sites.${site}.ports.backend" "$REGISTRY")
    local fport; fport=$(yq e ".sites.${site}.ports.frontend" "$REGISTRY")
    local pport; pport=$(yq e ".sites.${site}.ports.production" "$REGISTRY")
    read -r -p "Enter site description: " \
        -i "Webapp to..." -e description
    read -r -p "Enter repo URL: " \
        -i "http://github.com/theHousedev/" -e git_url
    yq -i "with(.;
        .tag = \"${site}\" |
        .name = \"${site^} Log\" |
        .description = \"${description}\" |
        .git_repo = \"${git_url}\" |
        .ports.backend = \"${bport}\" |
        .ports.frontend = \"${fport}\" |
        .ports.production = \"${pport}\"
    )" "${local_cfg}"
    OK "Created local config file: $local_cfg"
}

register() {
    local site="$1"
    local index; index=$(get_and_incr_site_count)
    local backend_base; backend_base=$(yq e '.global.ports.backend' "$REGISTRY")
    local backend_port; backend_port=$((index + backend_base))
    local production_base; production_base=$(yq e '.global.ports.production' "$REGISTRY")
    local production_port; production_port=$((index + production_base))
    local frontend_base; frontend_base=$(yq e '.global.ports.frontend' "$REGISTRY")
    local frontend_port; frontend_port=$((index + frontend_base))
    local rootdir; rootdir=${PWD}

    yq -i "with(.sites.${site};
        .index = ${index} |
        .tag = \"${site}\" |
        .name = \"${site^} Log\" |
        .status = \"stopped\" |
        .ports.backend = ${backend_port} |
        .ports.frontend = ${frontend_port} |
        .ports.production = ${production_port} |
        .paths.root = \"${rootdir}\" |
        .paths.frontend = \"${rootdir}/app\" |
        .paths.backend = \"${rootdir}/backend\" |
        .paths.config = \"${rootdir}/cfg.yaml\" |
        .paths.prod = \"${HOME}/sites/.prod/${site}\" |
        .last_up = null |
        .last_dev = null |
        .session_name = \"dev-${site}\"
    )" "${REGISTRY}"

    update_version_info "$site"
}

sanity_check() {
    local site="$1"
    # pass $site into a sanity check function which will
        # look up $site in script registry
        # fetch root, fdir, bdir from registry
        # validate at least these dirs exist; else errmsg
        # check for .env in root
}

# Core Functions ------------------------------------------------------------------------
z() { # catch-all testing function
    local site; site="$1"
    update_version_info "$site"
    update_timestamp "$site" "up"
}

list() {
    TODO "list"
}

new() {
    local site="$1"
    if has_local_config; then
        ERR "Local config already exists"
        echo -e "Use '${G}site stats $site${NC}' to view details.\n" >&2;
        return 1;
    else
        if [ "$site" != "${PWD##*/}" ]; then
            ERR "'$site' is invalid - must match present dir name."
            read -nr 1 -p "  Proceed using pwd name '${PWD##*/}'? (y/n) " proceed
            echo ""
            case "$proceed" in
                y|Y|yes|YES) site="${PWD##*/}" ;;
                n|N|no|NO) echo -e "Quitting setup."; return 1; ;;
                *) echo -e "Invalid response, quitting setup."; return 1; ;;
            esac
        fi

        echo -e "Registering '$site'..."
        if ! register "$site"; then
            ERR "Failed to register site, aborting..."
            exit 1
        else
            OK "Successfully registered site"
        fi

        echo -e "Configuring '$site'..."
        if ! make_local_config "$site"; then
            ERR "Failed to create local config; aborting..."
            exit 1
        fi
    fi
}

dev() {
    local site="$1"
    if ! sanity_check "$site"; then exit 1; fi
    local bpath; bpath=$(yq e ".sites.${site}.paths.backend" "$REGISTRY")
    local bport; bport=$(yq e ".sites.${site}.ports.backend" "$REGISTRY")
    local fpath; fpath=$(yq e ".sites.${site}.paths.frontend" "$REGISTRY")
    local fport; fport=$(yq e ".sites.${site}.ports.frontend" "$REGISTRY")
    local session; session=$(yq e ".sites.${site}.session_name" "$REGISTRY")

    local cmd; cmd="${2:-run}" # internal-only "run/stop"
    if [[ "$cmd" == "stop" ]]; then
        echo -e "Stopping '${G}$session${NC}'...";

        if tmux has-session -t "$session" 2>/dev/null; then
            if tmux kill-session -t "$session" 2>/dev/null; then
                OK "Stopped session: '${G}$session${NC}'"
            else
                ERR "Unable to kill session: '${G}$session${NC}'"
                exit 1
            fi
        else
            WARN "No session found: '${G}$session${NC}'"
        fi
    else
        if tmux has-session -t "$session" 2>/dev/null; then
            echo -e "Found existing tmux session: '${G}$session${NC}'"
        else
            if ! tmux new-session -d -s "$session" \
                -e "ENVIRONMENT=development" \
                -e "ALLOWED_ORIGIN=http://localhost:$fport" 2>/dev/null; then
                ERR "Failed to start tmux session."
                exit 1
            fi
            tmux split-window -h -t "${session}"
            OK "Started new tmux session: '${G}$session${NC}'"
        fi

        if ! tmux send-keys -t "${session}:0.0" "cd ${bpath} && go run ." Enter; then
            ERR "Failed to start '${G}${session}${NC}' backend process."
            exit 1
        fi
        OK "Backend service started"

        if ! tmux send-keys -t "${session}:0.1" "cd ${fpath} && npm run dev" Enter; then
            ERR "Failed to start '${G}${session}${NC}' frontend process."
            exit 1
        fi
        OK "Frontend service started"
        update_timestamp "$site" "dev"

        # TODO: details, localhost url, how to attach to tmux session, etc.
    fi
}

up() {
        local site="$1"
        local root_dir; root_dir=$(yq e ".sites.${site}.paths.root" "$REGISTRY")
        local prod_dir; prod_dir=$(yq e ".sites.${site}.paths.prod" "$REGISTRY")
        local prod_service; prod_service="site-${site}.service"
        local repo; repo=$(git -C "$root_dir" remote get-url origin)

        mkdir -p "$prod_dir"
        if [ -d "$prod_dir"/.git ]; then
            git -C "$prod_dir" fetch --all --tags
            git -C "$prod_dir" reset --hard origin/main
            git -C "$prod_dir" clean -fd
        else
            git clone "$repo" "$prod_dir"
            git -C "$prod_dir" switch main
        fi

		cp "$root_dir/cfg.yaml" "$prod_dir/cfg.yaml"

		if [ ! -f "$prod_dir/.env" ]; then
			local msg="No .env found in production. Create "
			msg+="${B}$prod_dir/.env${NC} before deployment."
			ERR "${msg}"
			return 1
		fi

		(cd "$prod_dir/backend" && go build -o ../"${site}"-backend) || {
            ERR "backend build failed"
            return 1
        }
        OK "Backend built successfully"
        (cd "$prod_dir/app" && npm ci && npm run build) || {
            ERR "frontend build failed"
            return 1
        }
        OK "Frontend built successfully"

        create_systemd_service "$site"
        sudo systemctl daemon-reload
        # if service isn't enabled, enable it
        if ! sudo systemctl is-enabled "$prod_service" 2>/dev/null; then
            sudo systemctl enable "$prod_service" 2>/dev/null
        fi
        sudo systemctl restart "$prod_service"

		if sudo systemctl restart "$prod_service"; then
			update_timestamp "$site" "up"
			OK "Production site started successfully"
		else
			local msg="Service failed to start - check "
			msg+="${B}journalctl -exu $prod_service${NC}"
			ERR "$msg"
			return 1
		fi
}

down() {
  local site="$1"
  local prod_service; prod_service="site-${site}.service"
  if sudo systemctl is-enabled "$prod_service" 2>/dev/null; then
    if sudo systemctl is-active "$prod_service" 2>/dev/null; then
      if sudo systemctl stop "$prod_service" 2>/dev/null; then
        OK "${G}$prod_service${NC} stopped successfully"
      else
        WARN "${G}$prod_service${NC} not stopped"
        return 1
      fi
    else
      WARN "${G}$prod_service${NC} not active"
      return 1
    fi
  else
    WARN "${G}$prod_service${NC} not enabled"
    return 1
  fi
} 

# stats ---------------------------------------------------------------------------------
stats_prod_short() {
  local site="$1"
  local prod; prod=$(yq e ".sites.${site}.paths.prod" "$REGISTRY")
  local svc="site-${site}.service"
  local active; active=$(sudo systemctl is-active "$svc" 2>/dev/null || true)
  local head; head=$(git -C "$prod" rev-parse --short HEAD 2>/dev/null || echo "n/a")
  local remote
  remote=$(git -C "$prod" rev-parse --short origin/main 2>/dev/null || echo "n/a")
  local dev; dev=$(yq e ".sites.${site}.last_dev" "$REGISTRY")
  local up; up=$(yq e ".sites.${site}.last_up" "$REGISTRY")
  echo -e "Prod: ${G}$active${NC} | commit: $head (remote: $remote)"
  echo -e "Dev: $dev | Up: $up"
}

stats() {
    local site="${1:-all}"

    if [ "$site" == "all" ]; then
        for each in $CFG_KEYS; do
            local title; title="[ ${DG}$each${NC} ]"
            echo -e "\n$title"
            stats_prod_short "$each"
        done
        echo ""
    else
        local title; title="[ ${DG}$site${NC} ]"
        echo -e "\n$title"
        stats_prod_short "$site"
        echo ""
    fi
}

logs() {
    TODO "logs"
}

help() {
    if [ "$1" == "short" ]; then
        echo -e "\nUsage: ${G}site <command> <site>${NC}"
        echo -e "Show all commands: '${G}site -h${NC}'\n"
        return 0;
    fi
    banner "Site Control Help"
    echo -e "Usage: ${G}site <command> <site>${NC}"
    echo -e "\nCommands:"
    echo -e "  ${G}help${NC}            Show this help message"
    echo -e "  ${G}list${NC}            List all sites"
    echo -e "  ${G}new <site>${NC}      Initialize a new site"
    echo -e "  ${G}dev <site>${NC}      Start a site in dev mode"
    echo -e "  ${G}up <site>${NC}       Start a site in production (pulls from main)"
    echo -e "  ${G}down <site>${NC}     Stop production site"
    echo -e "  ${G}stats <site>${NC}    Show stats for one (or all) sites"
    echo -e "  ${G}logs <site>${NC}     Show logs for one (or all) sites"
}

# main -----------------------------------------------------------------------------
main() {
    case "${1}" in
        -h|--help|help) help ;;
        new) new "$2" ;;
        list) list ;;
        dev) dev "$2" ;;
        stop) dev "$2" "stop" ;;
        up) up "$2" ;;
        down) down "$2" ;;
        stats) stats "$2" ;;
        logs) logs ;; z) z "$2" ;;
        *) help "short" ;;
    esac
}

main "$@"
